export const demo_meistari = [
  {
    vards: "Andris Kalniņš",
    iniciāļi: "AK",
    specialitate: "Santehniķis",
    kategorija: "Santehniskie darbi",
    regioni: ["Rīga", "Jūrmala"],
    rating: 4.8,
    atsauksmes_skaits: 34,
    cena_no: 40,
    subdomens: "https://andris-kalninsh.promeistars.lv",
  },
  {
    vards: "Sergejs Ivanovs",
    iniciāļi: "SI",
    specialitate: "Santehniķis",
    kategorija: "Santehniskie darbi",
    regioni: ["Rīga", "Mārupe"],
    rating: 4.6,
    atsauksmes_skaits: 28,
    cena_no: 35,
    subdomens: "https://sergejs-ivanovs.promeistars.lv",
  },
  {
    vards: "Māris Ozols",
    iniciāļi: "MO",
    specialitate: "Santehniķis",
    kategorija: "Santehniskie darbi",
    regioni: ["Jelgava", "Rīga"],
    rating: 4.9,
    atsauksmes_skaits: 51,
    cena_no: 45,
    subdomens: "https://maris-ozols.promeistars.lv",
  },
]
